export const layoutCode = `
import { Toaster } from "sonner";
import { AppSidebar } from "@/components/app-sidebar/app-sidebar";
import { SidebarFooter, SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import DashboardFooter from "@/components/DashBoardFooter";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { redirect } from "next/navigation";
import { Separator } from "@/components/ui/separator";
import { AppBreadcrumb } from "@/components/app-breadcrumb";
import { NavUser } from "@/components/app-sidebar/nav-user";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AdminLayout({ children }) {
  const session = await getServerSession(authOptions)

  if (!session?.user) {
    redirect('/')
  }
  return (
    <>
      <div>
        <SidebarProvider>
          <AppSidebar />
          <SidebarInset className='!bg-white'>
            <header className='border-color-grey flex h-20 shrink-0 items-center justify-between gap-2 border-b 
            shadow-[0_0_15px_-10px_black] transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12'>
              <div className='flex justify-between w-full '>
                <div className='flex items-center gap-2 px-4'>
                  <SidebarTrigger className='-ml-1' />
                  <Separator orientation='vertical' className='mr-2 h-4' />
                  <AppBreadcrumb />
                </div>
                <div>
                  <SidebarFooter>
                    <NavUser />
                  </SidebarFooter>
                </div>
              </div>
            </header>
            <div className='p-6 flex flex-1 flex-col rounded-sm bg-[#ececec]'>
              <Toaster />
              {children}
            </div>
            <DashboardFooter />
          </SidebarInset>
        </SidebarProvider>
      </div>
    </>

  );
}

`