
import { Toaster } from "sonner";
import { AppSidebar } from "@/components/app-sidebar/app-sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import DashboardFooter from "@/components/DashBoardFooter";
import UseContextProvider from "@/context/UseContextProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <>
      <div>
        <SidebarProvider>
          <AppSidebar />
          {/* <SidebarInset className='!bg-white'> */}
            {/* </header> */}
            <div className='mx-5 my-5 flex flex-1 flex-col gap-2 rounded-sm p-4 mt-20'>
              <Toaster />
              <UseContextProvider>
                {children}
              </UseContextProvider>
            </div>
            <DashboardFooter />
          {/* </SidebarInset> */}
        </SidebarProvider>
      </div>
    </>

  );
}
