export const routesUrl = {
  adminPannel: "/admin",
  userList: "/admin/users",
  inputField: "/admin/form/inputfield",
  selectField: "/admin/form/selectfield",
  datePicker: "/admin/form/datepicker",
  radioButton: "/admin/form/radiobutton",
  checkBox: "/admin/form/checkbox",
  textEditor: "/admin/form/editor",
  example: "/admin/form/example",
  accordian: "/admin/components/accordian",
  card: "/admin/components/card",
  tabs: "/admin/components/tab",
  paginationOrTable: "/admin/components/pagination-table",
  toolTip: '/admin/components/tooltip',
  popeover: '/admin/components/popover',
  dialog: '/admin/components/dialog',
  drawer: '/admin/components/drawer',
  sideBar: '/admin/components/sideBar',
  toaster: '/admin/components/toaster'
};
